/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_jorgeálvarez;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTree;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ofici
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuarioJd = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AlbumsExplorarLi = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        CancionesExplorarTb = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NombreCrearPlaylistTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ArbolVerPlaylistsJt = new javax.swing.JTree();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        EliminarUsuarioPm = new javax.swing.JPopupMenu();
        EliminarMi = new javax.swing.JMenuItem();
        EliminarAlbumsPm = new javax.swing.JPopupMenu();
        EliminarMi1 = new javax.swing.JMenuItem();
        PrincipalTp = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsuariosTb = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        UsernameUsuariosTf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        PasswordUsuariosTf = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        NombreUsuariosTf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EdadUsuariosTf = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        AlbumCancionesCb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GeneroCancionesTf = new javax.swing.JTextField();
        DuracionCancionestTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ArtistaCancionesTf = new javax.swing.JTextField();
        NombreCancionesTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreAlbumsTf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ArtistaAlbumsTf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        AlbumsLi = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        CancionesAlbumsTb = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UsernameLoginTf = new javax.swing.JTextField();
        PasswordLoginTf = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        AlbumsExplorarLi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        AlbumsExplorarLi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlbumsExplorarLiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(AlbumsExplorarLi);

        CancionesExplorarTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CancionesExplorarTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancionesExplorarTbMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(CancionesExplorarTb);

        jLabel4.setText("Agregar canciones a playlist con click derecho");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Explorar", jPanel7);

        jLabel5.setText("Nombre");

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(NombreCrearPlaylistTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreCrearPlaylistTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton3))
                .addContainerGap(410, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Crear Playlist", jPanel8);

        jScrollPane6.setViewportView(ArbolVerPlaylistsJt);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ver Playlists", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Ver favoritos", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Salir", jPanel11);

        javax.swing.GroupLayout UsuarioJdLayout = new javax.swing.GroupLayout(UsuarioJd.getContentPane());
        UsuarioJd.getContentPane().setLayout(UsuarioJdLayout);
        UsuarioJdLayout.setHorizontalGroup(
            UsuarioJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioJdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        UsuarioJdLayout.setVerticalGroup(
            UsuarioJdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UsuarioJdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        EliminarMi.setText("Eliminar");
        EliminarMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMiActionPerformed(evt);
            }
        });
        EliminarUsuarioPm.add(EliminarMi);

        EliminarMi1.setText("Eliminar");
        EliminarMi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMi1ActionPerformed(evt);
            }
        });
        EliminarAlbumsPm.add(EliminarMi1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrincipalTp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PrincipalTpStateChanged(evt);
            }
        });

        UsuariosTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Nombre", "Edad"
            }
        ));
        UsuariosTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuariosTbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UsuariosTb);

        jLabel12.setText("Eliminar en click derecho");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Nombre");

        jLabel16.setText("Edad");

        jButton7.setText("Crear usuario");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameUsuariosTf, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(PasswordUsuariosTf))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NombreUsuariosTf, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(EdadUsuariosTf))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombreUsuariosTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(UsernameUsuariosTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(PasswordUsuariosTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(EdadUsuariosTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Usuarios", jPanel1);

        jButton2.setText("Agregar canción");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Album");

        jLabel10.setText("Género");

        jLabel9.setText("Duración");

        jLabel8.setText("Artista");

        jLabel7.setText("Nombre");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreCancionesTf)
                            .addComponent(ArtistaCancionesTf)
                            .addComponent(DuracionCancionestTf)
                            .addComponent(GeneroCancionesTf)
                            .addComponent(AlbumCancionesCb, 0, 199, Short.MAX_VALUE))))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NombreCancionesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ArtistaCancionesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DuracionCancionestTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(GeneroCancionesTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AlbumCancionesCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Canciones", jPanel2);

        jLabel1.setText("Nombre");

        jLabel2.setText("Artista");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AlbumsLi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlbumsLiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(AlbumsLi);

        jLabel3.setText("Eliminar en click derecho");

        CancionesAlbumsTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Artista", "Duración", "Género", "Album"
            }
        ));
        jScrollPane5.setViewportView(CancionesAlbumsTb);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreAlbumsTf)
                            .addComponent(ArtistaAlbumsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NombreAlbumsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ArtistaAlbumsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );

        PrincipalTp.addTab("Albums", jPanel3);

        jLabel17.setText("Username");

        jLabel18.setText("Password");

        jButton4.setText("Iniciar sesión");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(57, 57, 57)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsernameLoginTf)
                    .addComponent(PasswordLoginTf, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addComponent(jButton4)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(UsernameLoginTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(PasswordLoginTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addContainerGap(373, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Log in", jPanel4);

        jButton5.setText("Guardar usuarios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Guardar usuarios", jPanel5);

        jButton6.setText("Cargar usuarios");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );

        PrincipalTp.addTab("Cargar usuarios", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PrincipalTp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PrincipalTp)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Usuarios.add(new Usuario());
        int pos = Usuarios.size() - 1;
        Usuarios.get(pos).setUsername(UsernameUsuariosTf.getText());
        Usuarios.get(pos).setPassword(PasswordUsuariosTf.getText());
        Usuarios.get(pos).setNombre(NombreUsuariosTf.getText());
        try {
            Usuarios.get(pos).setEdad(Integer.parseInt(EdadUsuariosTf.getText()));
        } catch (Exception e) {
        }
        UsernameUsuariosTf.setText("");
        PasswordUsuariosTf.setText("");
        NombreUsuariosTf.setText("");
        EdadUsuariosTf.setText("");
        actualizarTablaUsuarios();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            int pos = AlbumCancionesCb.getSelectedIndex();
            Albums.get(pos).getCanciones().add(new Cancion());
            int pos2 = Albums.get(pos).getCanciones().size() - 1;
            Albums.get(pos).getCanciones().get(pos2).setNombre(NombreCancionesTf.getText());
            Albums.get(pos).getCanciones().get(pos2).setArtista(ArtistaCancionesTf.getText());
            try {
                Albums.get(pos).getCanciones().get(pos2).setDuracion(Integer.parseInt(DuracionCancionestTf.getText()));
            } catch (Exception e) {
            }
            Albums.get(pos).getCanciones().get(pos2).setGenero(GeneroCancionesTf.getText());
            JOptionPane.showMessageDialog(this, "Agregado");
        } catch (Exception e) {
            Albums.clear();
            JOptionPane.showMessageDialog(this, "No hay albumes aún");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < Usuarios.size(); i++) {
            if (Usuarios.get(i).getUsername().equalsIgnoreCase(UsernameLoginTf.getText())
                    || Usuarios.get(i).getPassword().equals(PasswordLoginTf.getText())) {
                UsuarioActual = Usuarios.get(i);
                actualizarAlbums(AlbumsExplorarLi);
                UsuarioJd.setVisible(true);
                UsuarioJd.pack();
                try {
                    actualizarCanciones(null, CancionesExplorarTb);
                } catch (Exception e) {
                }
                actualizarArbol(ArbolVerPlaylistsJt);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void UsuariosTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosTbMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            EliminarUsuarioPm.show(UsuariosTb, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_UsuariosTbMouseClicked

    private void EliminarMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMiActionPerformed
        // TODO add your handling code here:
        try {
            Usuarios.remove(UsuariosTb.getSelectedRow());
            actualizarTablaUsuarios();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_EliminarMiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Albums.add(new Album());
        int pos = Albums.size() - 1;
        Albums.get(pos).setNombre(NombreAlbumsTf.getText());
        Albums.get(pos).setArtista(ArtistaAlbumsTf.getText());
        actualizarAlbums(AlbumsLi);
        JOptionPane.showMessageDialog(this, "Agregado");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AlbumsLiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlbumsLiMouseClicked
        // TODO add your handling code here:
        try {
            actualizarCanciones(Albums.get(AlbumsLi.getSelectedIndex()), CancionesAlbumsTb);
        } catch (Exception e) {
        }
        if (evt.isMetaDown()) {
            EliminarAlbumsPm.show(AlbumsLi, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_AlbumsLiMouseClicked

    private void EliminarMi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMi1ActionPerformed
        // TODO add your handling code here:
        try {
            Albums.remove(AlbumsLi.getSelectedIndex());

        } catch (Exception e) {
        }
    }//GEN-LAST:event_EliminarMi1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        File archivo = new File("./users.txt");
        AdminUsuarios admUsuarios = new AdminUsuarios(archivo);
        admUsuarios.setUsuarios(Usuarios);
        try {
            admUsuarios.escribirArchivo();
            JOptionPane.showMessageDialog(this, "Guardado");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        File archivo = new File("./users.txt");
        AdminUsuarios admUsuarios = new AdminUsuarios(archivo);
        admUsuarios.leerArchivo();
        Usuarios = admUsuarios.getUsuarios();
        actualizarTablaUsuarios();
        JOptionPane.showMessageDialog(this, "Cargado");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void AlbumsExplorarLiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlbumsExplorarLiMouseClicked
        // TODO add your handling code here:
        try {
            actualizarCanciones(Albums.get(AlbumsExplorarLi.getSelectedIndex()), CancionesExplorarTb);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_AlbumsExplorarLiMouseClicked

    private void CancionesExplorarTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancionesExplorarTbMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            try {
                temporal.add(Albums.get(AlbumsExplorarLi.getSelectedIndex()).getCanciones().get(CancionesExplorarTb.getSelectedRow()));
                JOptionPane.showMessageDialog(UsuarioJd, "Cancion agregada a playlist");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_CancionesExplorarTbMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Playlist p = new Playlist();
        p.setNombre(NombreCrearPlaylistTf.getText());
        p.setCancionest(temporal);
        UsuarioActual.getPlaylists().add(p);
        temporal.clear();
        actualizarArbol(ArbolVerPlaylistsJt);
        JOptionPane.showMessageDialog(UsuarioJd, "Agregado");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PrincipalTpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_PrincipalTpStateChanged
        // TODO add your handling code here:
        if (PrincipalTp.getSelectedIndex() == 1) {
            DefaultComboBoxModel m = new DefaultComboBoxModel();
            for (int i = 0; i < Albums.size(); i++) {
                m.addElement(Albums.get(i));
            }
            AlbumCancionesCb.setModel(m);
        }
    }//GEN-LAST:event_PrincipalTpStateChanged

    public void actualizarTablaUsuarios() {
        UsuariosTb.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Username", "Password", "Nombre", "Edad"
                }
        ));
        DefaultTableModel m = (DefaultTableModel) UsuariosTb.getModel();
        for (Usuario u : Usuarios) {
            Object[] fila = {
                u.getUsername(),
                u.getPassword(),
                u.getNombre(),
                u.getEdad(),};
            m.addRow(fila);
        }
        UsuariosTb.setModel(m);
    }

    public void actualizarAlbums(JList lista) {
        lista.setModel(new DefaultListModel());
        DefaultListModel modelo = new DefaultListModel();
        for (int i = 0; i < Albums.size(); i++) {
            modelo.addElement(Albums.get(i));
        }
        lista.setModel(modelo);
    }

    public void actualizarCanciones(Album album, JTable tabla) {
        tabla.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nombre", "Artista", "Duración", "Género", "Album"
                }
        ));
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        for (Cancion c : album.getCanciones()) {
            Object[] fila = {
                c.getNombre(),
                c.getArtista(),
                c.getDuracion(),
                c.getGenero(),
                album.getNombre()
            };
            modelo.addRow(fila);
        }
        tabla.setModel(modelo);
    }

    private void actualizarArbol(JTree arbol) {
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Playlists");
        for (Playlist p : UsuarioActual.getPlaylists()) {
            DefaultMutableTreeNode nodoPlaylist = new DefaultMutableTreeNode(p);
            for (Cancion c : p.getCancionest()) {
                DefaultMutableTreeNode nodoCancion = new DefaultMutableTreeNode(c);
                nodoPlaylist.add(nodoCancion);
            }
            raiz.add(nodoPlaylist);
        }
        DefaultTreeModel modeloArbol = new DefaultTreeModel(raiz);
        arbol.setModel(modeloArbol);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AlbumCancionesCb;
    private javax.swing.JList<String> AlbumsExplorarLi;
    private javax.swing.JList<String> AlbumsLi;
    private javax.swing.JTree ArbolVerPlaylistsJt;
    private javax.swing.JTextField ArtistaAlbumsTf;
    private javax.swing.JTextField ArtistaCancionesTf;
    private javax.swing.JTable CancionesAlbumsTb;
    private javax.swing.JTable CancionesExplorarTb;
    private javax.swing.JTextField DuracionCancionestTf;
    private javax.swing.JTextField EdadUsuariosTf;
    private javax.swing.JPopupMenu EliminarAlbumsPm;
    private javax.swing.JMenuItem EliminarMi;
    private javax.swing.JMenuItem EliminarMi1;
    private javax.swing.JPopupMenu EliminarUsuarioPm;
    private javax.swing.JTextField GeneroCancionesTf;
    private javax.swing.JTextField NombreAlbumsTf;
    private javax.swing.JTextField NombreCancionesTf;
    private javax.swing.JTextField NombreCrearPlaylistTf;
    private javax.swing.JTextField NombreUsuariosTf;
    private javax.swing.JTextField PasswordLoginTf;
    private javax.swing.JTextField PasswordUsuariosTf;
    private javax.swing.JTabbedPane PrincipalTp;
    private javax.swing.JTextField UsernameLoginTf;
    private javax.swing.JTextField UsernameUsuariosTf;
    private javax.swing.JDialog UsuarioJd;
    private javax.swing.JTable UsuariosTb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

    ArrayList<Usuario> Usuarios = new ArrayList();
    ArrayList<Album> Albums = new ArrayList();
    Usuario UsuarioActual = new Usuario();
    ArrayList<Cancion> temporal = new ArrayList();
}
